### ISSUE TITLE
should display warning that currently Nimble does not work out of the box

### ISSUE THREAD

**Issue by tkothe** [madebybright/madebybright.github.io#2]
as commented in madebybright/Nimble#15 it would be helpful if the website showed a hint that currently Nimble does not work out of the box but instead the instructions at https://medium.com/@brightco/roadblocks-ab6524617017#.ff9qxyr3z must be followed to get it to work.

**Comment by ethel-dev** [comment]
we're currently at the end of a deal with Wolfram that will continue working order. If this doesn't end soon, we'll add a hint to the website :+1:

**Comment by jshdm** [comment]
Fixed in [ae0e469](https://github.com/madebybright/Nimble/commit/44f94e273cfd1ed1dbfc64c96fc7ed6da63edd08).
